name: Get input with whitespace

on:
  workflow_dispatch:
    inputs:
      myinput:
        description: "Testing whitespace"
        type: bool
        required: true

jobs:
  check_whitespace:
    name: Validate input
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo "hotfix/${{ inputs.myinput }}"
        echo "hotfix/${{ inputs.myinput2 }}"
        echo "hotfix/${{ inputs.myinput3 }}"

        echo ${{ inputs.myinput }} | wc -c
        echo ${{ inputs.myinput2 }} | wc -c
        echo ${{ inputs.myinput3 }} | wc -c

        echo ${{ inputs.myinput }} | wc
        echo ${{ inputs.myinput2 }} | wc
        echo ${{ inputs.myinput3 }} | wc

        MYINPUT1="${{ inputs.myinput }}"
        MYINPUT2="${{ inputs.myinput2 }}"
        MYINPUT3="${{ inputs.myinput3 }}"

        echo ${#MYINPUT1}
        echo ${#MYINPUT2}
        echo ${#MYINPUT3}
